// <auto-generated />
namespace Nakladna.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class navigation_ids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(navigation_ids));
        
        string IMigrationMetadata.Id
        {
            get { return "201601272110059_navigation_ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
